<?php

/**
 * @file
 * Taxonomy Manager.
 *
 * Administration interface for managing taxonomy vocabularies.
 */

use Drupal\Core\Field\BaseFieldDefinition;

define('FD_TABLE', 'fd_category');
define('FD_DATA_ID', 'taxonomy-manager-data-form');
/**
 * Implements hook_admin_menu_map().
 */
function taxonomy_manager_admin_menu_map() {
  if (!user_access('administer taxonomy')) {
    return;
  }
  $map['admin/structure/taxonomy_manager/voc/%taxonomy_vocabulary_machine_name'] = [
    'parent' => 'admin/structure/taxonomy_manager/voc',
    'arguments' => [
      ['%taxonomy_vocabulary_machine_name' => array_keys(taxonomy_vocabulary_get_names())],
    ],
  ];
  return $map;
}

/**
 * Implements hook_help().
 */
function taxonomy_manager_help($path, $arg) {
  switch ($path) {
    case 'help.page.taxonomy_manager':
      $output = t("<p>The Taxonomy Manager provides an additional interface for managing vocabularies of the taxonomy module. It's especially very useful for long sets of terms.
                   The vocabulary is represented in a dynamic tree view.
                   It supports operation like mass adding and deleting of terms, fast weight editing, moving of terms in hierarchies, merging of terms and fast term data editing.
                   For more information on how to use please read the readme file included in the taxonomy_manager directory.</p>");
      $output .= t('<p><i>在原有 Taxonomy Manager基础上为分类添加`group_id` `module`字段，以`group_id`过滤显示结果</i></p>');
      return $output;
  }
}
/////////////////////////////////////PATCHED PART
/**
 * 分类Entity添加字段
 * hook_entity_base_field_info
 */
function taxonomy_manager_entity_base_field_info($entity_type)
{
    if ($entity_type->id() == 'taxonomy_term') {
        $fields = [];
        $fields['group_id'] = BaseFieldDefinition::create('integer')
            ->setLabel(t('平台编号'))
            ->setDescription(t('Group ID:所属平台编号'))
            ->setDisplayOptions('form', [
                'type' => 'string_textfield',
                'weight' => 4,
            ])
            ->setDisplayConfigurable('form', TRUE)
            ->setDisplayConfigurable('view', TRUE);
        $fields['module'] = BaseFieldDefinition::create('string')
            ->setLabel(t('内容分类'))
            ->setDescription(t('module:所属的类型-article/media/question'))
            ->setSettings([
                'max_length' => 50,
                'text_processing' => 0,
            ])
            ->setDisplayOptions('form', [
                'type' => 'string_textfield',
                'weight' => 4,
            ])
            ->setDisplayConfigurable('form', TRUE)
            ->setDisplayConfigurable('view', TRUE);
        return $fields;
    }
}

/**
 * 分类显示添加字段
 * hook_form_FORM_ID_alter
 */
function taxonomy_manager_form_taxonomy_overview_terms_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, &$form_id)
{
    $vocabulary_id = $form_state->getStorage()['taxonomy']['vocabulary']->id();
    $taxonomy_term = \Drupal::entityManager()->getStorage('taxonomy_term')->loadTree($vocabulary_id);
    $header = [
        'group_id' => t('Group ID'),
        'module' => t('Module')
    ];
    $form['terms']['#header'] = array_merge($form['terms']['#header'], $header);
    foreach ($form['terms'] as $k_form => $item_form) {
        if (preg_match("/^tid:(\d+):(\d+)$/", $k_form)) {
            $item_data = [];
            foreach($taxonomy_term as $k_tax => $item_tax) {
                if ($item_tax->tid == $item_form['#term']->id()) {
                    $item_data = [
                        'group_id' => [
                            '#type' => 'item',
                            '#title' => $item_tax->group_id
                        ],
                        'module' => [
                            '#type' => 'item',
                            '#title' => $item_tax->module
                        ]
                    ];
                    break;
                }
            }
            $form['terms'][$k_form] = array_merge($form['terms'][$k_form], $item_data);
        }
    }
    return $form;
}

/**
 * 修改Taxonomy Manager Form显示样式
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function taxonomy_manager_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, &$form_id)
{
    if ($form_id == 'taxonomy_manager.vocabulary_terms_form' && !empty($form['toolbar'])) {
        $vocabulary_id = $form['voc']['#value']->id();
        $taxonomy_term = \Drupal::entityManager()->getStorage('taxonomy_term')->loadTree($vocabulary_id);
        /*
         * 整理出选项内容
         */
        $group_ids = [];
        $modules =['All'];
        foreach($taxonomy_term as $term) {
            array_push($group_ids, $term->group_id);
            array_push($modules, $term->module);
        };
        $group_ids = array_unique($group_ids);
        sort($group_ids);
        $group_ids = array_combine($group_ids, $group_ids);

        $modules = array_unique($modules);
        sort($modules);
        $modules = array_combine($modules, $modules);

        // Add filter
        $filter['group_id'] = [
            '#type' => 'select',
            '#title' => t('Group ID'),
            '#options' => $group_ids,
            '#default_value' => array_values($group_ids)[0],
            '#size' => '5',
            '#prefix' => '<div class="taxonomy-manager-filter">',
            '#suffix' => '</div>',
            '#ajax' => [
                'callback' => 'Drupal\taxonomy_manager\Controller\FdController::filterCallback',
                'wrapper' => FD_DATA_ID
            ]
        ];
        $filter['module'] =[
            '#type' => 'select',
            '#title' => t('module'),
            '#options' => $modules,
            '#default_value' => array_values($modules)[0],
            '#size' => '5',
            '#prefix' => '<div class="taxonomy-manager-filter">',
            '#suffix' => '</div>',
            '#ajax' => [
                'callback' => 'Drupal\taxonomy_manager\Controller\FdController::filterCallback',
                'wrapper' => FD_DATA_ID
            ]
        ];
        $form['toolbar'] = array_merge($form['toolbar'], $filter);
        $form['taxonomy']['manager']['tree']['#id'] = FD_DATA_ID;
    }
}